using System.Text;
using System.Text.Json;
using OrgHierarchy.Components;

namespace OrgHierarchy.Demo;

internal enum SymbolLibraryIssueSeverity
{
    Error,
    Warning,
    Info
}

internal sealed record SymbolLibraryValidationIssue(
    SymbolLibraryIssueSeverity Severity,
    string Code,
    string FileName,
    string Message);

internal sealed class SymbolLibraryValidationReport
{
    public static SymbolLibraryValidationReport Empty { get; } = new(0, Array.Empty<SymbolLibraryValidationIssue>());

    public SymbolLibraryValidationReport(int fileCount, IReadOnlyList<SymbolLibraryValidationIssue> issues)
    {
        FileCount = fileCount;
        Issues = issues;
    }

    public int FileCount { get; }
    public IReadOnlyList<SymbolLibraryValidationIssue> Issues { get; }
    public int ErrorCount => Issues.Count(issue => issue.Severity == SymbolLibraryIssueSeverity.Error);
    public int WarningCount => Issues.Count(issue => issue.Severity == SymbolLibraryIssueSeverity.Warning);
    public int InfoCount => Issues.Count(issue => issue.Severity == SymbolLibraryIssueSeverity.Info);
}

internal static class SymbolLibraryValidator
{
    private const float MinimumCoordinate = -0.1f;
    private const float MaximumCoordinate = 1.1f;

    public static SymbolLibraryValidationReport ValidateFiles(
        IEnumerable<string> files,
        JsonSerializerOptions jsonOptions)
    {
        var fileList = files.Distinct(StringComparer.OrdinalIgnoreCase).ToArray();
        var issues = new List<SymbolLibraryValidationIssue>();
        var definitions = new List<(string FileName, SymbolLibraryDefinition Definition)>();

        foreach (var file in fileList)
        {
            try
            {
                var definition = JsonSerializer.Deserialize<SymbolLibraryDefinition>(
                    File.ReadAllText(file, Encoding.UTF8),
                    jsonOptions);
                if (definition == null)
                {
                    Add(issues, SymbolLibraryIssueSeverity.Error, "JSON_NULL", file, "The file does not contain a symbol definition.");
                    continue;
                }

                definitions.Add((file, definition));
                ValidateDefinition(file, definition, issues);
            }
            catch (Exception exception)
            {
                Add(issues, SymbolLibraryIssueSeverity.Error, "JSON_INVALID", file, exception.Message);
            }
        }

        ValidateDuplicates(definitions, issues);
        return new SymbolLibraryValidationReport(
            fileList.Length,
            issues
                .OrderBy(issue => issue.Severity)
                .ThenBy(issue => Path.GetFileName(issue.FileName), StringComparer.CurrentCultureIgnoreCase)
                .ThenBy(issue => issue.Code, StringComparer.OrdinalIgnoreCase)
                .ToArray());
    }

    private static void ValidateDefinition(
        string file,
        SymbolLibraryDefinition definition,
        ICollection<SymbolLibraryValidationIssue> issues)
    {
        if (definition.Version > SymbolLibraryDefinition.CurrentSchemaVersion)
            Add(issues, SymbolLibraryIssueSeverity.Error, "SCHEMA_NEWER", file, $"Schema version {definition.Version} is newer than supported version {SymbolLibraryDefinition.CurrentSchemaVersion}.");
        else if (definition.Version < SymbolLibraryDefinition.CurrentSchemaVersion)
            Add(issues, SymbolLibraryIssueSeverity.Info, "SCHEMA_OLD", file, $"Schema version {definition.Version} will be upgraded when the symbol is saved.");

        if (!definition.HasStoredLibraryId)
            Add(issues, SymbolLibraryIssueSeverity.Warning, "ID_MISSING", file, $"LibraryId is missing. Derived ID: {definition.GetEffectiveLibraryId()}.");
        else if (!Guid.TryParseExact(definition.LibraryId.Trim(), "N", out _))
            Add(issues, SymbolLibraryIssueSeverity.Warning, "ID_FORMAT", file, "LibraryId should use the 32-character GUID format generated by the designer.");

        if (definition.LibraryVersion < 1)
            Add(issues, SymbolLibraryIssueSeverity.Error, "REVISION_INVALID", file, "LibraryVersion must be 1 or greater.");

        if (string.IsNullOrWhiteSpace(definition.Name))
            Add(issues, SymbolLibraryIssueSeverity.Warning, "NAME_MISSING", file, "Name is empty.");

        ValidateIdentity(file, definition, issues);
        ValidateFileName(file, definition, issues);

        var expectedFrame = SymbolFrameMapping.GetFrameShape(
            definition.Affiliation,
            definition.PhysicalDomain,
            definition.OperatingState);
        if (definition.FrameShape != expectedFrame)
            Add(issues, SymbolLibraryIssueSeverity.Warning, "FRAME_METADATA", file, $"FrameShape {definition.FrameShape} does not match {definition.Affiliation}/{definition.PhysicalDomain}/{definition.OperatingState}.");

        if (definition.Commands.Count == 0)
        {
            Add(issues, SymbolLibraryIssueSeverity.Error, "COMMANDS_EMPTY", file, "The symbol has no drawing commands.");
            return;
        }

        for (var index = 0; index < definition.Commands.Count; index++)
            ValidateCommand(file, definition.Commands[index], index, issues);
    }

    private static void ValidateIdentity(
        string file,
        SymbolLibraryDefinition definition,
        ICollection<SymbolLibraryValidationIssue> issues)
    {
        var domain = definition.GetEffectivePhysicalDomain();
        var missing = domain switch
        {
            SymbolPhysicalDomain.LandUnit => definition.SymbolRole switch
            {
                OrbatEquipmentSymbolRole.Modifier1 => IsUnspecified(definition.LandUnitModifier1Type),
                OrbatEquipmentSymbolRole.Modifier2 => IsUnspecified(definition.LandUnitModifier2Type),
                OrbatEquipmentSymbolRole.EchelonIndicator => IsUnspecified(definition.EchelonType),
                _ => definition.GetEffectiveUnitMainFunction() == OrbatUnitMainFunction.Unspecified
            },
            SymbolPhysicalDomain.Equipment => definition.SymbolRole switch
            {
                OrbatEquipmentSymbolRole.Modifier1 => IsUnspecified(definition.Modifier1Type),
                OrbatEquipmentSymbolRole.Modifier2 => IsUnspecified(definition.Modifier2Type),
                OrbatEquipmentSymbolRole.MobilityIndicator => IsUnspecified(definition.MobilityType),
                _ => IsUnspecified(definition.EquipmentFunction)
            },
            _ => true
        };

        if (missing)
            Add(issues, SymbolLibraryIssueSeverity.Error, "IDENTITY_MISSING", file, "The domain/role-specific function or modifier name is unspecified.");
    }

    private static void ValidateFileName(
        string file,
        SymbolLibraryDefinition definition,
        ICollection<SymbolLibraryValidationIssue> issues)
    {
        var expectedPrefix = definition.GetEffectivePhysicalDomain() switch
        {
            SymbolPhysicalDomain.LandUnit => definition.SymbolRole switch
            {
                OrbatEquipmentSymbolRole.Modifier1 => "LandUnit.Modifier1.",
                OrbatEquipmentSymbolRole.Modifier2 => "LandUnit.Modifier2.",
                OrbatEquipmentSymbolRole.EchelonIndicator => "LandUnit.Amplifier.B.",
                _ => "LandUnit."
            },
            SymbolPhysicalDomain.Equipment => definition.SymbolRole switch
            {
                OrbatEquipmentSymbolRole.Modifier1 => "Equipment.Modifier1.",
                OrbatEquipmentSymbolRole.Modifier2 => "Equipment.Modifier2.",
                OrbatEquipmentSymbolRole.MobilityIndicator => "Equipment.Amplifier.R.",
                _ => "Equipment."
            },
            _ => string.Empty
        };

        var name = Path.GetFileName(file);
        if (!string.IsNullOrEmpty(expectedPrefix)
            && !name.StartsWith(expectedPrefix, StringComparison.OrdinalIgnoreCase))
            Add(issues, SymbolLibraryIssueSeverity.Warning, "FILE_PREFIX", file, $"Expected the file name to start with '{expectedPrefix}'.");
    }

    private static void ValidateCommand(
        string file,
        SymbolDrawCommand command,
        int index,
        ICollection<SymbolLibraryValidationIssue> issues)
    {
        var label = $"Command {index + 1} ({command.Kind})";
        var points = new[] { command.Start, command.End, command.Control1, command.Control2 }
            .Concat(command.Points ?? Enumerable.Empty<SymbolPoint>());
        if (points.Any(point => !float.IsFinite(point.X) || !float.IsFinite(point.Y))
            || !float.IsFinite(command.Radius)
            || !float.IsFinite(command.FontSize)
            || !float.IsFinite(command.StrokeWidth)
            || !float.IsFinite(command.RotationDegrees))
        {
            Add(issues, SymbolLibraryIssueSeverity.Error, "COMMAND_NONFINITE", file, $"{label} contains NaN or Infinity.");
            return;
        }

        if (command.StrokeWidth <= 0f)
            Add(issues, SymbolLibraryIssueSeverity.Warning, "STROKE_INVALID", file, $"{label} has a non-positive stroke width.");
        if (command.Kind == SymbolDrawCommandKind.Text && string.IsNullOrWhiteSpace(command.Text))
            Add(issues, SymbolLibraryIssueSeverity.Warning, "TEXT_EMPTY", file, $"{label} has no text.");
        if (command.Kind is SymbolDrawCommandKind.Path or SymbolDrawCommandKind.Polyline
            && (command.Points?.Count ?? 0) < 2)
            Add(issues, SymbolLibraryIssueSeverity.Error, "PATH_TOO_SHORT", file, $"{label} requires at least two points.");
        if (command.Kind is SymbolDrawCommandKind.Circle or SymbolDrawCommandKind.Dot && command.Radius < 0f)
            Add(issues, SymbolLibraryIssueSeverity.Error, "RADIUS_INVALID", file, $"{label} has a negative radius.");

        var bounds = command.GetNormalizedVisualBounds();
        if (!float.IsFinite(bounds.Left)
            || !float.IsFinite(bounds.Top)
            || !float.IsFinite(bounds.Right)
            || !float.IsFinite(bounds.Bottom))
        {
            Add(issues, SymbolLibraryIssueSeverity.Error, "BOUNDS_NONFINITE", file, $"{label} produces invalid bounds.");
        }
        else if (bounds.Left < MinimumCoordinate
            || bounds.Top < MinimumCoordinate
            || bounds.Right > MaximumCoordinate
            || bounds.Bottom > MaximumCoordinate)
        {
            Add(issues, SymbolLibraryIssueSeverity.Warning, "BOUNDS_OUTSIDE", file, $"{label} extends outside the expected drawing range (-0.1 to 1.1).");
        }
    }

    private static void ValidateDuplicates(
        IReadOnlyList<(string FileName, SymbolLibraryDefinition Definition)> definitions,
        ICollection<SymbolLibraryValidationIssue> issues)
    {
        foreach (var group in definitions
            .Where(item => item.Definition.HasStoredLibraryId)
            .GroupBy(item => item.Definition.GetEffectiveLibraryId(), StringComparer.OrdinalIgnoreCase)
            .Where(group => group.Count() > 1))
        {
            var names = string.Join(", ", group.Select(item => Path.GetFileName(item.FileName)));
            foreach (var item in group)
                Add(issues, SymbolLibraryIssueSeverity.Error, "ID_DUPLICATE", item.FileName, $"LibraryId is shared by: {names}.");
        }

        foreach (var group in definitions
            .GroupBy(item => item.Definition.GetIdentityKey(), StringComparer.OrdinalIgnoreCase)
            .Where(group => group.Count() > 1))
        {
            var names = string.Join(", ", group.Select(item => Path.GetFileName(item.FileName)));
            foreach (var item in group)
                Add(issues, SymbolLibraryIssueSeverity.Warning, "IDENTITY_DUPLICATE", item.FileName, $"Logical identity is also used by: {names}.");
        }
    }

    private static bool IsUnspecified(string? value) =>
        string.IsNullOrWhiteSpace(value)
        || value.Equals("Unspecified", StringComparison.OrdinalIgnoreCase);

    private static void Add(
        ICollection<SymbolLibraryValidationIssue> issues,
        SymbolLibraryIssueSeverity severity,
        string code,
        string file,
        string message) =>
        issues.Add(new SymbolLibraryValidationIssue(severity, code, file, message));
}

internal sealed class SymbolLibraryValidationForm : Form
{
    private readonly ListView _issueList = new();
    private readonly Label _summaryLabel = new() { Dock = DockStyle.Fill, TextAlign = ContentAlignment.MiddleLeft };

    public SymbolLibraryValidationForm(SymbolLibraryValidationReport report)
    {
        Text = "Symbol Library Validation";
        StartPosition = FormStartPosition.CenterParent;
        MinimumSize = new Size(900, 520);
        Size = new Size(1160, 700);

        _issueList.Dock = DockStyle.Fill;
        _issueList.View = View.Details;
        _issueList.FullRowSelect = true;
        _issueList.GridLines = true;
        _issueList.HideSelection = false;
        _issueList.Columns.Add("Severity", 86);
        _issueList.Columns.Add("Code", 150);
        _issueList.Columns.Add("File", 280);
        _issueList.Columns.Add("Message", 570);

        foreach (var issue in report.Issues)
        {
            var item = new ListViewItem(issue.Severity.ToString())
            {
                ForeColor = issue.Severity switch
                {
                    SymbolLibraryIssueSeverity.Error => Color.Firebrick,
                    SymbolLibraryIssueSeverity.Warning => Color.DarkOrange,
                    _ => SystemColors.GrayText
                },
                ToolTipText = issue.FileName
            };
            item.SubItems.Add(issue.Code);
            item.SubItems.Add(Path.GetFileName(issue.FileName));
            item.SubItems.Add(issue.Message);
            _issueList.Items.Add(item);
        }

        _summaryLabel.Text = $"Scanned {report.FileCount} file(s): {report.ErrorCount} error(s), {report.WarningCount} warning(s), {report.InfoCount} info.";
        Controls.Add(CreateLayout(report));
    }

    private Control CreateLayout(SymbolLibraryValidationReport report)
    {
        var root = new TableLayoutPanel
        {
            Dock = DockStyle.Fill,
            ColumnCount = 1,
            RowCount = 3,
            Padding = new Padding(10)
        };
        root.RowStyles.Add(new RowStyle(SizeType.Absolute, 38));
        root.RowStyles.Add(new RowStyle(SizeType.Percent, 100));
        root.RowStyles.Add(new RowStyle(SizeType.Absolute, 42));
        root.Controls.Add(_summaryLabel, 0, 0);
        root.Controls.Add(_issueList, 0, 1);

        var buttons = new FlowLayoutPanel
        {
            Dock = DockStyle.Fill,
            FlowDirection = FlowDirection.RightToLeft,
            WrapContents = false
        };
        var closeButton = new Button { Text = "Close", AutoSize = true, DialogResult = DialogResult.OK };
        var copyButton = new Button { Text = "Copy report", AutoSize = true, Enabled = report.Issues.Count > 0 };
        copyButton.Click += (_, _) => CopyReport(report);
        buttons.Controls.Add(closeButton);
        buttons.Controls.Add(copyButton);
        root.Controls.Add(buttons, 0, 2);
        AcceptButton = closeButton;
        CancelButton = closeButton;
        return root;
    }

    private static void CopyReport(SymbolLibraryValidationReport report)
    {
        var lines = new[]
        {
            $"Scanned {report.FileCount} file(s): {report.ErrorCount} error(s), {report.WarningCount} warning(s), {report.InfoCount} info."
        }.Concat(report.Issues.Select(issue =>
            $"{issue.Severity}\t{issue.Code}\t{issue.FileName}\t{issue.Message}"));
        Clipboard.SetText(string.Join(Environment.NewLine, lines));
    }
}